### ISSUE TITLE
[Meta] Trial run spin-up on DINO inputs

### ISSUE THREAD

**Issue by Etienne-Meunier** [m2lines/nemo-spinup-forecast#18]
- [x] Run 50 years simulation of DINO 1deg on Cambridge Cluster 
- [x] #19 Load the output files from DINO in python spin up code (possible adaptation of the code)  : (gridT_1month : ssh, gridT_ 1year {Salinity, Temperature}) 
- [x] (Later) : Run acceleration and use the spin-up result as initialisation to DINO
