### ISSUE TITLE
[META] Implement code testing strategy

### ISSUE THREAD

**Issue by ma595** [m2lines/nemo-spinup-forecast#8]
Adopt `pytest` to run integration and unit tests. We'll use `pytest` to :

- [x] Implement smoke test. #20 
- [x] Add unit tests to Forecast #59. 
- [x] Add unit tests to Dimensionality reduction. 
- [ ] Integration tests to show end-to-end use of forecast.
